### ISSUE TITLE
Error: hiredis@0.1.17 install: `node-gyp rebuild`

### ISSUE THREAD

**Issue by selfagency** [redis/hiredis#505]
```
5255 verbose stack Error: hiredis@0.1.17 install: `node-gyp rebuild`
5255 verbose stack Exit status 1
5255 verbose stack     at EventEmitter.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/lib/utils/lifecycle.js:214:16)
5255 verbose stack     at emitTwo (events.js:87:13)
5255 verbose stack     at EventEmitter.emit (events.js:172:7)
5255 verbose stack     at ChildProcess.<anonymous> (/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/lib/node_modules/npm/lib/utils/spawn.js:24:14)
5255 verbose stack     at emitTwo (events.js:87:13)
5255 verbose stack     at ChildProcess.emit (events.js:172:7)
5255 verbose stack     at maybeClose (internal/child_process.js:818:16)
5255 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
5256 verbose pkgid hiredis@0.1.17
5257 verbose cwd /tmp/deployment/application
5258 error Linux 4.1.13-18.26.amzn1.x86_64
5259 error argv "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/node" "/opt/elasticbeanstalk/node-install/node-v4.2.3-linux-x64/bin/npm" "--production" "install"
5260 error node v4.2.3
5261 error npm  v2.14.7
5262 error code ELIFECYCLE
5263 error hiredis@0.1.17 install: `node-gyp rebuild`
5263 error Exit status 1
5264 error Failed at the hiredis@0.1.17 install script 'node-gyp rebuild'.
5264 error This is most likely a problem with the hiredis package,
5264 error not with npm itself.
5264 error Tell the author that this fails on your system:
5264 error     node-gyp rebuild
5264 error You can get their info via:
5264 error     npm owner ls hiredis
5264 error There is likely additional logging output above.
5265 verbose exit [ 1, true ]
```

**Comment by badboy** [comment]
Please upgrade to the latest hiredis release on npm: v0.5.0
