### ISSUE TITLE
memory leak 

### ISSUE THREAD

**Issue by zhza** [redis/hiredis#544]
The problem is in a single thread, the program will run out of this problem, there is another "sds.c" file, 221 lines of s_realloc leak; I do not know what caused this, I need help!
```
Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7ffff42e0700 (LWP 9497)]
0x00007ffff68cf1d7 in raise () from /lib64/libc.so.6
Missing separate debuginfos, use: debuginfo-install glib2-2.46.2-4.el7.x86_64 glibc-2.17-157.el7_3.4.x86_64 keyutils-libs-1.5.8-3.el7.x86_64 krb5-libs-1.14.1-27.el7_3.x86_64 libcom_err-1.42.9-9.el7.x86_64 libffi-3.0.13-18.el7.x86_64 libgcc-4.8.5-11.el7.x86_64 libselinux-2.5-6.el7.x86_64 libstdc++-4.8.5-11.el7.x86_64 openssl-libs-1.0.1e-60.el7_3.1.x86_64 pcre-8.32-15.el7_2.1.x86_64 zlib-1.2.7-17.el7.x86_64
(gdb) bt
#0  0x00007ffff68cf1d7 in raise () at /lib64/libc.so.6
#1  0x00007ffff68d08c8 in abort () at /lib64/libc.so.6
#2  0x00007ffff690ef07 in __libc_message () at /lib64/libc.so.6
#3  0x00007ffff6916503 in _int_free () at /lib64/libc.so.6
#4  0x000000000040d588 in redisBufferWrite (c=c@entry=0x63e200, done=done@entry=0x7ffff42df374)
    at cache/redis/hiredis/hiredis.c:849
#5  0x000000000040d815 in redisGetReply (c=c@entry=0x63e200, reply=reply@entry=0x7ffff42df3a8)
    at cache/redis/hiredis/hiredis.c:882
#6  0x000000000040d877 in __redisBlockForReply (c=c@entry=0x63e200)
    at cache/redis/hiredis/hiredis.c:996
#7  0x000000000040dac6 in redisvCommand (c=c@entry=0x63e200, format=format@entry=0x41cafd "HSET %s %s %s", ap=ap@entry=0x7ffff42df418) at cache/redis/hiredis/hiredis.c:1006
#8  0x0000000000413481 in redis_vcommand (redisocket=0x63e1a0, inst=0x6393e0, format=format@entry=0x41cafd "HSET %s %s %s", ap=ap@entry=0x7ffff42df418) at cache/redis/hiredispool.c:487
#9  0x00000000004044bd in cache_command (context=context@entry=0x7ffff42dfd90, format=format@entry=0x41cafd "HSET %s %s %s") at tsd_cache.c:43
#10 0x0000000000404656 in cache_hash_set (context=context@entry=0x7ffff42dfd90, key=key@entry=0x41cb61 "real_time_location", field=field@entry=0x7ffff42dfc40 "869057077685", value=value@entry=0x7ffff42df7f0 "\"869057077685\":{\"alarm\":0,\"status\":0,\"latitude\":24488263,\"longitude\":118177379,\"height\":22,\"speed\":0,\"direction\":0,\"time\":\"2017-09-07 09:38:14\",\"ext\":{\"1\":100,\"2\":99,\"3\":98,\"4\":97,\"17\":{\"type\":0,\"area"...) at tsd_cache.c:171
#11 0x0000000000404c87 in cache_location (context=context@entry=0x7ffff42dfd90, terminal=terminal@entry=0x7ffff42dfc40 "869057077685", location=location@entry=0x7ffff42dfc50, extnum=extnum@entry=12 '\f', ext=ext@entry=0x7fffec002430) at tsd_cache.c:428
#12 0x00000000004089a6 in answer_location (head=head@entry=0x7ffff42dfcc0, body=0x7fffec002200 "", answer_size=answer_size@entry=0x7ffff42dfcb6, answer_data=answer_data@entry=0x7fffec000d80 "~\200\001", redis_context=redis_context@entry=0x7ffff42dfd90) at tsd_protocol.c:496
#13 0x0000000000409f02 in answer (head=head@entry=0x7ffff42dfcc0, body=<optimized out>, answer_size=answer_size@entry=0x7ffff42dfcb6, answer_data=answer_data@entry=0x7fffec000d80 "~\200\001", redis_context=redis_context@entry=0x7ffff42dfd90) at tsd_protocol.c:1300
#14 0x00000000004063ff in tsd_tcp_protocol_parse (ep=ep@entry=27, info=info@entry=0x7fffd40008c0, buffer=buffer@entry=0x7fffec000d80 "~\200\001", len=len@entry=103, redis_context=redis_context@entry=0x7ffff42dfd90) at tsd_tcp_server.c:249
#15 0x000000000040660c in tsd_tcp_socket_recv (ep=ep@entry=27, info=info@entry=0x7fffd40008c0, buffer=buffer@entry=0x7fffec000d80 "~\200\001", size=size@entry=4096, redis_context=redis_context@entry=0x7ffff42dfd90) at tsd_tcp_server.c:390
#16 0x00000000004067de in tsd_tcp_epoll_call (arg=<optimized out>) at tsd_tcp_server.c:640
#17 0x00007ffff78c5dc5 in start_thread () at /lib64/libpthread.so.0
#18 0x00007ffff699176d in clone () at /lib64/libc.so.6
```

**Comment by badboy** [comment]
Without a minimal test case to reproduce there's not much I can do.
