### ISSUE TITLE
segmentation fault in sdscatlen during pipelining

### ISSUE THREAD

**Issue by janemba** [redis/hiredis#913]
Hi,

I have an issue while using pipeline for a huge amount of data. I'm getting a segmentation fault after `redisvAppendCommand` has been called approximately 26828974 times.

Here is the backtrace:
```
0x00007ffff77e3434 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
(gdb) bt
#0  0x00007ffff77e3434 in __memmove_avx_unaligned_erms () from /lib64/libc.so.6
#1  0x00007ffff7e014d9 in sdscatlen () from /usr/lib64/libhiredis.so.0.13
#2  0x00007ffff7e00f20 in __redisAppendCommand () from /usr/lib64/libhiredis.so.0.13
#3  0x00007ffff7e00fa1 in redisvAppendCommand () from /usr/lib64/libhiredis.so.0.13
#4  0x00000000004695b9 in xxx (xxx) at xxx.c:80
#5  0x000000000046bca7 in xxx (xxx) at xxx.c:82
#6  xxx (vargp=0x7ffff0001e20) at xxx.c:151
#7  0x00007ffff785206b in start_thread () from /lib64/libpthread.so.0
#8  0x00007ffff777b68f in clone () from /lib64/libc.so.6

```

**Comment by michael-grunder** [comment]
It's not really possible to say without more information.  I'm going to close this since it's been inactive for some time, but if you can provide code to replicate the crash I'm happy to re-open and take a look.
